# Generated by Django 5.2.8 on 2026-01-10 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

# usuwa tagi z notatek (zmiana zdania)
# dodaje nowy model Task

class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_category_tag_note_delete_comment_delete_post"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="note",
            name="tags",
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("is_done", models.BooleanField(default=False)),
                (
                    "note",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="blog.note",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Tag",
        ),
    ]
